config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  
  resources :adjustments
  resources :wallets

  resources :loans do
    member do
      post :approve
      post :reject
      post :adjust
      patch :repay
      patch :update_status
      patch :accept_reject
    end
  end

  root to: 'loans#index'
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :admin_user, class_name: 'AdminUser', optional: true, foreign_key: :admin_user_id
  validates :balance, numericality: { greater_than_or_equal_to: 0 }

  def credit(amount)
    self.balance += amount
    save!
  end

  def debit(amount)
    if amount > self.balance
      self.balance = 0
    else
      self.balance -= amount
    end
    save!
  end
end

app/controllers/wallets_controller.rb
class WalletsController < InheritedResources::Base
  # skip_before_action :authenticate_user!, except: [:create]
  private

    def wallet_params
      params.require(:wallet).permit(:balance, :user_id)
    end

end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/wallets/_form.html.erb
<%= form_with(model: wallet) do |form| %>
  <% if wallet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(wallet.errors.count, "error") %> prohibited this wallet from being saved:</h2>

      <ul>
        <% wallet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :balance, style: "display: block" %>
    <%= form.text_field :balance %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/wallets/_wallet.html.erb
<div id="<%= dom_id wallet %>">
  <p>
    <strong>Balance:</strong>
    <%= wallet.balance %>
  </p>

  <p>
    <strong>User:</strong>
    <%= wallet.user_id %>
  </p>

</div>

app/views/wallets/edit.html.erb
<h1>Editing wallet</h1>

<%= render "form", wallet: @wallet %>

<br>

<div>
  <%= link_to "Show this wallet", @wallet %> |
  <%= link_to "Back to wallets", wallets_path %>
</div>

app/views/wallets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Wallets</h1>

<div id="wallets">
  <% @wallets.each do |wallet| %>
    <%= render wallet %>
    <p>
      <%= link_to "Show this wallet", wallet %>
    </p>
  <% end %>
</div>

<%= link_to "New wallet", new_wallet_path %>

app/views/wallets/new.html.erb
<h1>New wallet</h1>

<%= render "form", wallet: @wallet %>

<br>

<div>
  <%= link_to "Back to wallets", wallets_path %>
</div>

app/views/wallets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @wallet %>

<div>
  <%= link_to "Edit this wallet", edit_wallet_path(@wallet) %> |
  <%= link_to "Back to wallets", wallets_path %>

  <%= button_to "Destroy this wallet", @wallet, method: :delete %>
</div>