config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  
  resources :adjustments
  resources :wallets

  resources :loans do
    member do
      post :approve
      post :reject
      post :adjust
      patch :repay
      patch :update_status
      patch :accept_reject
    end
  end

  root to: 'loans#index'
end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :user
  belongs_to :admin_user, optional: true
  has_many :adjustments

  enum state: {
    requested: 0,
    approved: 1,
    open: 2,
    closed: 3,
    rejected: 4,
    waiting_for_adjustment_acceptance: 5,
    readjustment_requested: 6
  }
  
  validates :amount, presence: true
  validates :interest_rate, presence: true

  after_initialize :set_default_state, if: :new_record?

  def set_default_state
    self.state ||= :requested
  end

  def self.ransackable_attributes(auth_object = nil)
    ["amount", "created_at", "id", "interest_rate", "state", "updated_at", "user_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["user", "admin"]
  end

  def update_interest_rate(new_interest_rate)
    if self.interest_rate != new_interest_rate
      self.interest_rate = new_interest_rate
      self.state = :readjustment_requested
      save!
    end
  end
end

app/controllers/loans_controller.rb
class LoansController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :authorize_admin, only: [:approve, :reject, :adjust]
  before_action :set_loan, only: [:update, :approve, :reject, :adjust, :update_status, :repay]

  def index
    if current_user.admin?
      @loans = Loan.all
    else
      loans = current_user.loans
      @approved_loans = loans.where(state: 'approved')
      @loans = loans.where.not(state: "approved")
    end
  end

  def accept_reject
    @loan = Loan.find_by(id: params[:id])
    if @loan.update(state: params[:value])
      if @loan.state == 'open' 
        current_balance = current_user.wallet.balance
        current_admin_balance = AdminUser.last.wallet.balance
        current_user.wallet.update(balance: current_balance + @loan.amount)
        AdminUser.last.wallet.update(balance: current_admin_balance - @loan.amount)
      end
      redirect_to loans_path, notice: "Loan status is now set to  #{params[:value]}"
    else
      redirect_to loans_path, notice: "Loan status has not set to #{params[:value]}"
    end
  end

  def new
    @loan = Loan.new
  end

  def update 
    if @loan.amount.to_f != update_params[:amount].to_f || 
      @loan.interest_rate.to_f != update_params[:interest_rate].to_f

      @loan.update(amount: update_params[:amount], interest_rate: update_params[:interest_rate])
      flash[:success] = "Loan's now set to Readjustment Requested" 
      @loan.update(state: "readjustment_requested")
      redirect_to loan_path(@loan)
    elsif @loan.update(update_params)
      flash[:success] = "Loan details are updated successfully" 
      redirect_to loan_path(@loan)
    else
      flash[:error] = "Error updating Loans #{@loan.errors.full_messages} "
    end
  end

  def create
    return redirect_to loans_path, alert: "Your loan amount exceeds your wallet balance"  if loan_params[:amount].present? && loan_params[:amount]&.to_i >= current_user.wallet.balance
    @loan = current_user.loans.new(loan_params)
    if @loan.save
      redirect_to loans_path, notice: 'Loan requested successfully.'
    else
      render :new
    end
  end

  def approve
    loan.update(state: :approved)
    redirect_to admin_dashboard_path, notice: 'Loan approved.'
  end

  def reject
    loan.update(state: :rejected)
    redirect_to admin_dashboard_path, notice: 'Loan rejected.'
  end

  def adjust
    adjustment = loan.adjustments.create!(amount: params[:amount], interest_rate: params[:interest_rate])
    
    loan.update_interest_rate(params[:interest_rate])
    
    redirect_to admin_dashboard_path, notice: 'Loan adjusted.'
  end

  def update_status
    if @loan.user == current_user && @loan.state == 'readjustment_requested'
      @loan.update(state: :waiting_for_adjustment_acceptance)
      redirect_to loans_path, notice: 'Loan status updated successfully.'
    else
      redirect_to loans_path, alert: 'You are not authorized to update this loan status.'
    end
  end

  def repay
    amount_to_repay = @loan.total_amount_due
    if current_user.wallet.balance >= amount_to_repay
      current_user.wallet.debit(amount_to_repay)
      AdminUser.last.wallet.credit(amount_to_repay)
      @loan.update(state: "closed")
      flash[:success] = "Your Loan is now closed"
      redirect_to loans_path  
    else
      flash[:alert] = "Unfortunately, you don't have sufficient balance to repay this loan at this time."
      redirect_to loans_path
    end
  end

  private

  def loan_params
    params.require(:loan).permit(:amount, :interest_rate, :user_id)
  end

  def update_params
    params.require(:loan).permit(:id, :amount, :interest_rate, :user_id)
  end

  def set_loan
    @loan = Loan.find(params[:id])
  end

  def authorize_admin
    redirect_to root_path, alert: 'Access denied.' unless current_user.admin?
  end
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/_form.html.erb
<%= form_with(model: loan) do |form| %>
  <% if loan.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
        <% loan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.label :interest_rate, style: "display: block" %>
    <%= form.text_field :interest_rate %>
  </div>

  <div>
    <%= form.submit 'Request Loan' %>
  </div>
<% end %>

app/views/loans/_loan.html.erb
<div id="<%= dom_id loan %>">
  <p>
    <strong>Amount:</strong>
    <%= loan.amount %>
  </p>

  <p>
    <strong>Interest rate:</strong>
    <%= loan.interest_rate %>
  </p>

  <p> 
    <strong>Total Due:</strong>
    <%= loan.total_amount_due %>
  </p>

  <p>
    <strong>State:</strong>
    <%= loan.state %>
  </p>

  <p>
    <strong>User:</strong>
    <%= loan.user_id %>
  </p>

</div>

app/views/loans/edit.html.erb
<h1>Editing loan</h1>

<%= render "form", loan: @loan %>

<br>

<div>
  <%= link_to "Show this loan", @loan %> |
  <%= link_to "Back to loans", loans_path %>
</div>

app/views/loans/index.html.erb
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <h1>Admin Dashboard</h1>
    <p>Welcome, <%= current_user.email %></p>
    <p>Admin Wallet Balance: <%= number_to_currency(current_user.wallet.balance) %></p>

    <h2>All Loans</h2>
    <table class="table">
      <thead>
        <tr>
          <th>Loan ID</th>
          <th>User</th>
          <th>Amount</th>
          <th>Interest Rate</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <% @loans.each do |loan| %>
          <tr>
            <td><%= loan.id %></td>
            <td><%= loan.user.email %></td>
            <td><%= number_to_currency(loan.amount) %></td>
            <td><%= loan.interest_rate %>
            <td><%= loan.state %></td>
            <td><%= link_to 'Show', loan %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to "New loan", new_loan_path, class: 'btn btn-primary' %>
    <%= link_to "Manage Users", admin_users_path, class: 'btn btn-secondary' %>
  <% else %>
    <h1>User Dashboard</h1>
    <p>Welcome, <%= current_user.email %></p>
    <p>User Wallet Balance: <%= number_to_currency(current_user.wallet&.balance) %></p>

    <h2>Your Loans</h2>
    <table class="table">
      <thead>
        <tr>
          <th>Loan ID</th>
          <th>Amount</th>
          <th>Status</th>
          <th>Interest Rate</th>
          <th>Amount Due</th>
        </tr>
      </thead>
      <tbody>
        <% @loans.each do |loan| %>
          <tr>
            <td><%= loan.id %></td>
            <td><%= number_to_currency(loan.amount) %></td>
            <td><%= loan.state %></td>
            <td><%= loan.interest_rate %>
            <td><%= loan.total_amount_due %></td>
            <td><%= link_to 'Show', loan %>
              <%= link_to 'Edit', edit_loan_path(loan) %>
              <%= link_to 'Repay', repay_loan_path(loan), method: :patch, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to repay this loan?' } if loan.state == 'open' %>
            <% if loan.state == 'waiting_for_adjustment_acceptance' %>
              <%= link_to 'Accept', accept_reject_loan_path(loan, value: 'open'), method: :patch, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to accept this loan?' } %>
              <%= link_to 'Reject', accept_reject_loan_path(loan, value: 'rejected'), method: :patch, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to reject this loan?' } %></td>
            <% end %>

          </tr>
        <% end %>
      </tbody>
    </table>

    <h2>Approved Loans</h2>
    <table class="table">
      <thead>
        <tr>
          <th>Loan ID</th>
          <th>Amount</th>
          <th>Status</th>
          <th>Interest Rate</th>
        </tr>
      </thead>
      <tbody>
        <% @approved_loans.each do |loan| %>
          <tr>
            <td><%= loan.id %></td>
            <td><%= number_to_currency(loan.amount) %></td>
            <td><%= loan.state %></td>
            <td><%= loan.interest_rate %></td>
            <td>
              <%= link_to 'Show', loan %>
              <%= link_to 'Accept', accept_reject_loan_path(loan, value: 'open'), method: :patch, class: 'btn btn-success', data: { confirm: 'Are you sure you want to accept this loan?' } %>
              <%= link_to 'Reject', accept_reject_loan_path(loan, value: 'rejected'), method: :patch, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to reject this loan?' } %>
            </td>
          </tr>
        <% end  if @approved_loans.any? %> 
      </tbody>
    </table>
    <%= link_to "New loan", new_loan_path, class: 'btn btn-primary' %>
  <% end %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
<% else %>
  <%= link_to "Login", new_user_session_path, class: 'btn btn-primary' %>
<% end %>

app/views/loans/new.html.erb
<h1>Request Loan</h1>

<%= render "form", loan: @loan %>

<br>

<div>
  <%= link_to "Back to loans", loans_path %>
</div>

app/views/loans/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @loan %>

<% if @loan.state == 'readjustment_requested' %>
  <%= button_to "Approve Readjustment", update_status_loan_path(@loan), method: :patch, class: 'btn btn-success' %>
<% end %>

<%= button_to "Repay Loan", repay_loan_path(@loan), method: :patch, class: 'btn btn-success' if @loan.state == 'open' %>


<div>
  <%= link_to "Edit this loan", edit_loan_path(@loan) %> |
  <%= link_to "Back to loans", loans_path %>

  <%= button_to "Destroy this loan", @loan, method: :delete %>
</div>