config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  
  resources :adjustments
  resources :wallets

  resources :loans do
    member do
      post :approve
      post :reject
      post :adjust
      patch :repay
      patch :update_status
      patch :accept_reject
    end
  end

  root to: 'loans#index'
end

app/models/adjustment.rb
class Adjustment < ApplicationRecord
  belongs_to :loan
end

app/controllers/adjustments_controller.rb
class AdjustmentsController < InheritedResources::Base

  private

    def adjustment_params
      params.require(:adjustment).permit(:loan_id, :amount, :interest_rate)
    end

end

app/helpers/adjustments_helper.rb
module AdjustmentsHelper
end

app/views/adjustments/_adjustment.html.erb
<div id="<%= dom_id adjustment %>">
  <p>
    <strong>Loan:</strong>
    <%= adjustment.loan_id %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= adjustment.amount %>
  </p>

  <p>
    <strong>Interest rate:</strong>
    <%= adjustment.interest_rate %>
  </p>

</div>

app/views/adjustments/_form.html.erb
<%= form_with(model: adjustment) do |form| %>
  <% if adjustment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(adjustment.errors.count, "error") %> prohibited this adjustment from being saved:</h2>

      <ul>
        <% adjustment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :loan_id, style: "display: block" %>
    <%= form.text_field :loan_id %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.label :interest_rate, style: "display: block" %>
    <%= form.text_field :interest_rate %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/adjustments/edit.html.erb
<h1>Editing adjustment</h1>

<%= render "form", adjustment: @adjustment %>

<br>

<div>
  <%= link_to "Show this adjustment", @adjustment %> |
  <%= link_to "Back to adjustments", adjustments_path %>
</div>

app/views/adjustments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Adjustments</h1>

<div id="adjustments">
  <% @adjustments.each do |adjustment| %>
    <%= render adjustment %>
    <p>
      <%= link_to "Show this adjustment", adjustment %>
    </p>
  <% end %>
</div>

<%= link_to "New adjustment", new_adjustment_path %>

app/views/adjustments/new.html.erb
<h1>New adjustment</h1>

<%= render "form", adjustment: @adjustment %>

<br>

<div>
  <%= link_to "Back to adjustments", adjustments_path %>
</div>

app/views/adjustments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @adjustment %>

<div>
  <%= link_to "Edit this adjustment", edit_adjustment_path(@adjustment) %> |
  <%= link_to "Back to adjustments", adjustments_path %>

  <%= button_to "Destroy this adjustment", @adjustment, method: :delete %>
</div>